[package]
name = "waysmoke-shell"
version = "2020.5.0"
authors = ["Greg V <greg@unrelenting.technology>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
futures = "0.3"
glib = "0.9"

wstk = { path = "../wstk" }
